### PR TITLE
Support carbon 1.26 for laravel 5.5 and use GitHub Actions instead travis-ci

### PR DESCRIPTION
**Pull request by veneliniliev**
Please enable github actions for testing with them :)

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks! Let's see if these tests run correctly now :-)

**Comment by freekmurze** [comment]
Seems like everything works ok, thanks again!
https://github.com/spatie/test-time/commit/251e12e68c1cc8364994bcca3d947b8925264540/checks?check_suite_id=412718976

**Comment by veneliniliev** [comment]
please release a new version, so i can also do and "laravel-webhook-server"

**Comment by freekmurze** [comment]
done

**Pull request merged**
